# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20160614_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes_url',
            name='url',
            field=models.CharField(max_length=350),
        ),
    ]
